apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "env-cleaner.fullname" . }}
  labels:
    {{- include "env-cleaner.labels" . | nindent 4 }}
data:
  config.yml: |-
  {{- .Values.configuration | toYaml | nindent 4 }}
